### PR TITLE
Areas

### PR DESCRIPTION
**Pull request by taikedz**
This change adds the ability to display the owner of the space in conjunction with ShadowNinja's `areas` HUD

Conditional on ShadowNinja accepting the corresponding pull request https://github.com/ShadowNinja/areas/pull/19

### CODE REVIEW

**Comment by taikedz** [comment]
https://github.com/ShadowNinja/areas/pull/19 has been pulled

This would now be safe to add if desired?

**Comment by tenplus1** [comment]
I like the idea of having it show protected owner in corner of screen, but the way areas handles it is to call globalstep repeatedly and in doing so with protector redo will cause undue lag, especially with many players.

**Comment by taikedz** [comment]
I could envisage instead adding a configurable timeout for the callback itself - would that address the concern?

**Comment by taikedz** [comment]
OK I see the problem here in adding a timer at this level. I might go prod ShadowNinja on a configurable glboalstep time...

As for this PR however, I have added the feature as a deliberate opt-in, so that becomes a conscientious choice...

**Pull request closed without merging**
